In [4]:
import numpy as np

### 1차원 배열

In [3]:
array1d = np.array([1,2,3])
print('array1d type:', type(array1d))
print('array1d array', array1d.shape)

array1 type: <class 'numpy.ndarray'>
array1 array (3,)


### 2차원 배열. 차원은 행의 개수

In [4]:
array2d = np.array([[1,2,3],[4,5,6]])
print('array2d type:', type(array2d))
print('array2d array', array2d.shape)

array2 type: <class 'numpy.ndarray'>
array2 array (2, 3)


In [5]:
array2d = np.array([[1,2,3]])
print('array2d type:', type(array2d))
print('array2d array', array2d.shape)

array2d type: <class 'numpy.ndarray'>
array2d array (1, 3)


### arrange :: 0~N까지 1차원 배열을 가지는 nparray를 만든다.

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros :: default값이 0인 nparray를 만든다. 

In [9]:
zero_array = np.zeros((3,2), dtype='int32')
print('zero_array shape:' , zero_array.shape)
zero_array

zero_array shape: (3, 2)


array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

### ones :: default값이 1.0인 nparray를 만든다. 

In [10]:
one_array = np.ones((3,2))
print(one_array.dtype, one_array.shape)
one_array

float64 (3, 2)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### reshape :: nparray의 행렬을 바꾼다. 

In [18]:
org_array = np.arange(10)
org_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
org_array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### reshape :: 행 또는 열에 -1을 지정하면 열 또는 행의 값에 따라 지정해준다. 

In [16]:
org_array.reshape(-1,5) #열의 개수를 5개로 지정했으니 행의 개수는 2개가 된다. 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
org_array.reshape(-1,1) #열의 개수를 1개로 지정했으니 행의 개수는 10개가 된다. 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### 3차원 배열

In [20]:
array8n = np.arange(8)
array3d = array8n.reshape(2,2,2)

array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### (:) 연산자로 nparray를 슬라이싱해, 꺼내올 수 있다. 

In [22]:
array1to10 = np.arange(1,10)
array1to10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
array1to10[0:2]

array([1, 2])

### python에서 -1은 마지막 인덱스를 의미한다. 

In [24]:
array1to10[-1] #가장 마지막 값이 추출된다.

9

In [26]:
array2d = array1to10.reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
array2d[0,1]

2

In [32]:
array2d[0:2, 0:2]

[[1 2]
 [4 5]]


### 팬시인덱싱 : 연속되지 않은 행/렬 데이터를 뽑아낼 때 유용하다. 

In [36]:
array2d[[0,1], 2]
 

array([3, 6])

In [37]:
array2d[[0,1],0:2]


array([[1, 2],
       [4, 5]])

In [38]:
array2d[[0,1]]


array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
array2d[[0,2], 2] #0,2행에 있는 2번째 열을 뽑는다.

array([3, 9])

### 불린인덱싱 : nparray 중 조건에 맞는 값만 추출해 새로운 nparray를 만들 수 있다. 

In [40]:
conditionArray = array1to10[array1to10>5]
conditionArray

array([6, 7, 8, 9])

### 정렬 : 원본데이터를 변경할 수도 있고(void), 새로운 데이터를 반환할 수도 있다(nparray)

In [42]:
org_array = np.array([3,1,9,4])
org_array

array([3, 1, 9, 4])

In [44]:
sorted_array = np.sort(org_array) #immutable 
print("org_array:" , org_array) #org_array는 안변함
sorted_array

org_array: [3 1 9 4]


array([1, 3, 4, 9])

In [45]:
org_array.sort #void. 원본데이터를 변경함. 
org_array

array([3, 1, 9, 4])

### desc로 정렬하려면 [::-1]

In [46]:
np.sort(org_array)[::-1]

array([9, 4, 3, 1])

### 2차원 정렬 :: ROW만 정렬하려면 axis=0, Column만 정렬하려면 axis=1

In [48]:
array2d = np.array([[8,12], [7,1]])
np.sort(array2d, axis=0)

array([[ 7,  1],
       [ 8, 12]])

### argsort :: 정렬된 행렬의 인덱스를 반환

In [60]:
np.argsort(array2d)

array([[0, 1],
       [1, 0]])

### dot :: 행렬 내적 

In [50]:
A = np.array([[1,2,3],[4,5,6]]) #2*3
B = np.array([[7,8],[9,10],[11,12]]) #3*2
np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

### transpose :: 행렬 전치

In [51]:
print(A)
print(np.transpose(A))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
